name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Add Dropbox app identifier
        shell: bash
        run: echo "dropbox.app_key = \"${{ secrets.DROPBOX_APP_KEY }}\"" >> app.properties
      
      - name: Build APK
        run: ./gradlew assembleDebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: orgzly-debug-app
          path: '**/*.apk'
